name: Hello Actions

on:
  push:
    branches:
    - main
  pull_request:
    types: [closed]
    
  workflow_dispatch:
  
env:
  name: Roybo
jobs:
  build:
  
    runs-on: ubuntu-latest
    env:
      name: Ray V.
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          echo Hello, $name!
          echo Actor: ${{ github.actor }}
          echo Commited By: ${{ github.event.commits[0].author.name }}
        
        
  dump:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  pull_request_only:
  
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo Hi, $name.

